# Generated by Django 2.0.7 on 2018-08-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0004_auto_20180627_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnews',
            name='news_link',
            field=models.URLField(unique=True),
        ),
    ]
