# Generated by Django 2.0.7 on 2018-08-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0006_auto_20180806_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnews',
            old_name='title',
            new_name='post_title',
        ),
    ]
