# Generated by Django 2.0.7 on 2018-08-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrap', '0007_auto_20180806_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortnews',
            old_name='datetime',
            new_name='post_datetime',
        ),
    ]
